name: Build Hugo Blog

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Hugo
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true  # Use the extended version of Hugo if your blog uses SCSS

      # Step 3: Build the Hugo site
      - name: Build Hugo site
        run: hugo 

      - name: List contents of public folder
        run: ls -l public/

      # Step 4: Save the build output (for debugging)
      - name: Upload public folder
        uses: actions/upload-artifact@v4
        with:
          name: tech-blog
          path: public/*

       # Step 5: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}  # Use the secret here
          aws-region: us-east-1  # Replace with your AWS region

     
 
